src/main/java/com/odebar/webprovider/repository/entity/Order.java
package com.odebar.webprovider.repository.entity;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;

public class Order extends AbstractEntity<Integer> {
    private Integer userId;
    private List<OrderItem> items;
    private Timestamp created;

    public Order() {

    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public List<OrderItem> getItems() {
        return items;
    }

    public void setItems(List<OrderItem> items) {
        this.items = items;
    }

    public Timestamp getCreated() {
        return created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public BigDecimal getTotalCost() {
        BigDecimal cost = BigDecimal.ZERO;
        if (items != null) {
            for (OrderItem item : items) {
                cost = cost.add(item.getTariff().getPrice());
            }
        }
        return cost;
    }

    @Override
    public String toString() {
        return String.format("Order [id=%s, idAccount=%s, items=%s, created=%s]", getId(), userId, items, created);
    }
}

src/main/webapp/WEB-INF/JSP/fragment/aside.jsp
<%--
  Created by IntelliJ IDEA.
  User: Odessa_Bear
  Date: 18.12.2021
  Time: 23:35
  To change this template use File | Settings | File Templates.
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="web-provider" tagdir="/WEB-INF/tags" %>
<%@ page contentType="text/html;charset=UTF-8" %>
<div class="visible-xs-block xs-option-container">
    <a class="pull-right" data-toggle="collapse" href="#serviceCatalog">Service Catalog <span
            class="caret"></span></a>
    <a data-toggle="collapse" href="#findTariffs">Find Tariffs <span class="caret"></span></a>
</div>
<!-- Categories-->
<div id="serviceCatalog" class="panel panel-success collapse">
    <div class="panel-heading">Service Catalog</div>
    <div class="list-group">
        <c:forEach var="category" items="${CATEGORIES_LIST}">
            <a href="${pageContext.request.contextPath}/tariffs${category.url}"
               class="list-group-item ${selectedCategoryUrl == category.url ? 'active' : '' }">
                    ${category.name}
            </a>
        </c:forEach>
    </div>
</div>
<!-- Sorting form -->
<form class="sort" action="/sort">
    <div id="findTariffs" class="panel panel-success collapse">
        <div class="panel-heading">Filters</div>
        <div class="panel-body">
            <div class="more-options">
                <a data-toggle="collapse" href="#sortingOptions"> Choose Filter <span class="caret"></span></a>
            </div>
        </div>
        <div id="sortingOptions" class="collapse">
            <div class="panel-heading">Alphabetic sorting</div>
            <div class="panel-body tariffs">
                <div class="form-group">
                    <div class="checkbox">
                        <label><input type="checkbox" name="ta" value="1" class="sorting-option">A ->
                            Z</label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label><input type="checkbox" name="ta" value="2" class="sorting-option">Z ->
                            A</label>
                    </div>
                </div>
            </div>
            <div class="panel-heading">Price sorting</div>
            <div class="panel-body tariffs">
                <div class="form-group">
                    <div class="checkbox">
                        <label><input type="checkbox" name="ta" value="1" class="sorting-option">Up </label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label><input type="checkbox" name="ta" value="2" class="sorting-option">Down
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<!-- /sorting form -->
<!-- <div class="panel panel-primary">
<div class="panel-heading">Admin Panel</div>
<div class="list-group">
<a href="#" class="list-group-item">Create Tariff</a>
<a href="#" class="list-group-item">Update Tariff</a>
<a href="#" class="list-group-item">Delete Tariff</a>
<a href="#" class="list-group-item">Register Client</a>
<a href="#" class="list-group-item">Block Client</a>
<a href="#" class="list-group-item">Unblock Client</a>
</div>
</div> -->

src/main/webapp/WEB-INF/JSP/fragment/footer.jsp
<%--
  Created by IntelliJ IDEA.
  User: Odessa_Bear
  Date: 18.12.2021
  Time: 23:42
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" %>
<div class="container">
    <p class="text-center">WebProvider-project. Oleksander Mykhailov, 2021</p>
</div>

src/main/webapp/WEB-INF/JSP/fragment/header.jsp
<%--
  Created by IntelliJ IDEA.
  User: Odessa_Bear
  Date: 18.12.2021
  Time: 23:29
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#providerNav" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/tariffs">TAKOGONET</a>
        </div>
        <div class="collapse navbar-collapse" id="providerNav">
            <ul id="currentShoppingCart" class="nav navbar-nav navbar-right ${CURRENT_SHOPPING_CART == null ? 'hidden' : ''}">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i> Shopping cart (<span class="total-count">${CURRENT_SHOPPING_CART.totalCount}</span>)<span class="caret"></span>
                    </a>
                    <div class="dropdown-menu shopping-cart-desc">
                        Total count: <span class="total-count">${CURRENT_SHOPPING_CART.totalCount}</span><br>
                        Total cost: <span class="total-cost">${CURRENT_SHOPPING_CART.totalCost}</span><br>
                        <a href="/shopping-cart" class="btn btn-primary btn-block">View cart</a>
                    </div>
                </li>
            </ul>
            <a href="login-page.html" class="btn btn-primary navbar-btn navbar-right sign-in"> Sign in</a>
        </div>
    </div>
</nav>

src/main/webapp/WEB-INF/JSP/fragment/tariffs-list.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%--
  Created by IntelliJ IDEA.
  User: Odessa_Bear
  Date: 19.12.2021
  Time: 0:16
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" %>
<c:forEach var="tariff" items="${tariffs}">
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xlg-2">
        <!-- tariff DATA -->
        <div id="tariff${tariff.id}" class="panel panel-default tariff ">
            <div class="panel-body">
                <div class="thumbnail">
                    <img src="https://via.placeholder.com/400" alt="${tariff.name}">
                    <div class="desc">
                        <div class="cell">
                            <p><span class="title">Details</span>${tariff.description}</p>
                        </div>
                    </div>
                </div>
                <h4 class="name">${tariff.name}</h4>
                <div class="code">Code: ${tariff.id}</div>
                <div class="price">${tariff.price}</div>
                <a class="btn btn-primary pull-right buy-btn" data-id-tariff="${tariff.id}">Buy</a>
                <div class="list-group">
                                        <span class="list-group-item"> <small>Category:</small> <span
                                                class="category">${tariff.category}</span></span>
                </div>
            </div>
        </div>
        <!-- tariff DATA -->
    </div>
</c:forEach>